package feishu

import (
	"reflect"
	"testing"

	imgateway "github.com/odysseythink/pantheon/im-gateway"
)

// Expected values below were generated by executing the original Python
// source (octop_gateway/channels/feishu.py: _build_post_content,
// _guess_feishu_file_type, _extract_post_parts) on the same inputs.

// ---------------------------------------------------------------------------
// buildPostContent (Python feishu.py:626 _build_post_content)
// ---------------------------------------------------------------------------

func TestBuildPostContent(t *testing.T) {
	row := func(text string) [][]map[string]any {
		return [][]map[string]any{{{"tag": "md", "text": text}}}
	}
	cases := []struct {
		name string
		in   string
		want map[string]any
	}{
		{"plain", "hello", map[string]any{"zh_cn": map[string]any{"content": row("hello")}}},
		{"empty becomes marker", "", map[string]any{"zh_cn": map[string]any{"content": row("[empty]")}}},
		// fence right after a non-newline char gets a \n inserted
		{"fence mid-text", "a```b", map[string]any{"zh_cn": map[string]any{"content": row("a\n```b")}}},
		// fence already preceded by \n is left alone
		{"fence after newline", "a\n```", map[string]any{"zh_cn": map[string]any{"content": row("a\n```")}}},
		{"fence twice", "x```y```z", map[string]any{"zh_cn": map[string]any{"content": row("x\n```y\n```z")}}},
		// a leading fence has no preceding char and is unchanged
		{"fence at start", "```", map[string]any{"zh_cn": map[string]any{"content": row("```")}}},
		{"cjk before fence", "代码```块", map[string]any{"zh_cn": map[string]any{"content": row("代码\n```块")}}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := buildPostContent(tc.in)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("buildPostContent(%q)\n got %#v\nwant %#v", tc.in, got, tc.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// guessFeishuFileType (Python feishu.py:893 _guess_feishu_file_type)
// ---------------------------------------------------------------------------

func TestGuessFeishuFileType(t *testing.T) {
	cases := []struct {
		filename string
		mime     string
		want     string
	}{
		{"a.opus", "audio/ogg", "opus"},
		{"a.OGG", "audio/ogg", "opus"}, // case-insensitive
		{"x.MP4", "video/mp4", "mp4"},
		{"v.avi", "video/x-msvideo", "mp4"},
		{"v.mov", "video/quicktime", "mp4"},
		{"v.mkv", "video/x-matroska", "mp4"},
		{"d.pdf", "application/pdf", "pdf"},
		{"d.doc", "application/msword", "doc"},
		{"d.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "doc"},
		{"s.xls", "application/vnd.ms-excel", "xls"},
		{"s.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xls"},
		{"p.ppt", "application/vnd.ms-powerpoint", "ppt"},
		{"p.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "ppt"},
		{"noext", "application/octet-stream", "stream"}, // unknown extension fallback
		{"a.txt", "text/plain", "stream"},
		{"", "application/octet-stream", "stream"},           // empty filename
		{"archive.tar.gz", "application/gzip", "stream"},     // multi-suffix: only the last counts (and .gz is unmapped)
		{"doc", "application/msword", "stream"},              // bare word without dot is not an extension
	}
	for _, tc := range cases {
		if got := guessFeishuFileType(tc.filename, tc.mime); got != tc.want {
			t.Errorf("guessFeishuFileType(%q, %q) = %q, want %q", tc.filename, tc.mime, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// extractPostParts (Python feishu.py:1193 _extract_post_parts)
// ---------------------------------------------------------------------------

func extractText(t *testing.T, contentData map[string]any, messageID string) (string, []imgateway.ContentPart) {
	t.Helper()
	return extractPostParts(contentData, messageID)
}

func TestExtractPostPartsTags(t *testing.T) {
	cases := []struct {
		name        string
		contentData map[string]any
		messageID   string
		wantText    string
		wantMedia   []imgateway.ContentPart // nil means "expect none"
	}{
		{"text tag", map[string]any{"content": []any{[]any{map[string]any{"tag": "text", "text": "Hello"}}}}, "m1", "Hello", nil},
		{"md tag", map[string]any{"content": []any{[]any{map[string]any{"tag": "md", "text": "md text"}}}}, "m1", "md text", nil},
		{"title", map[string]any{"title": "T", "content": []any{[]any{map[string]any{"tag": "text", "text": "Hello"}}}}, "m1", "T\nHello", nil},
		{"a with text", map[string]any{"content": []any{[]any{map[string]any{"tag": "a", "href": "https://x", "text": "link"}}}}, "m1", "link(https://x)", nil},
		{"a without text", map[string]any{"content": []any{[]any{map[string]any{"tag": "a", "href": "u"}}}}, "m1", "u(u)", nil},
		{"a without href", map[string]any{"content": []any{[]any{map[string]any{"tag": "a", "text": "t"}}}}, "m1", "t", nil},
		{"at user_name", map[string]any{"content": []any{[]any{map[string]any{"tag": "at", "user_name": "Bob"}}}}, "m1", "@Bob", nil},
		{"at user_id fallback", map[string]any{"content": []any{[]any{map[string]any{"tag": "at", "user_id": "u1"}}}}, "m1", "@u1", nil},
		{"emotion emoji_type", map[string]any{"content": []any{[]any{map[string]any{"tag": "emotion", "emoji_type": "SMILE"}}}}, "m1", "[SMILE]", nil},
		{"emotion emoji fallback", map[string]any{"content": []any{[]any{map[string]any{"tag": "emotion", "emoji": "OK"}}}}, "m1", "[OK]", nil},
		{"emotion default", map[string]any{"content": []any{[]any{map[string]any{"tag": "emotion"}}}}, "m1", "[emoji]", nil},
		{"img without message_id", map[string]any{"content": []any{[]any{map[string]any{"tag": "img", "image_key": "v3_imgkey"}}}}, "", "[Image: v3_imgkey]", nil},
		{"media without message_id", map[string]any{"content": []any{[]any{map[string]any{"tag": "media", "file_key": "fk1"}}}}, "", "[File: fk1]", nil},
		{"code_block with language", map[string]any{"content": []any{[]any{map[string]any{"tag": "code_block", "language": "go", "text": "x := 1"}}}}, "m1", "```go\nx := 1\n```", nil},
		{"code_block no language", map[string]any{"content": []any{[]any{map[string]any{"tag": "code_block", "text": "plain"}}}}, "m1", "```\nplain\n```", nil},
		{"nested zh_cn payload", map[string]any{"zh_cn": map[string]any{"title": "T", "content": []any{[]any{map[string]any{"tag": "text", "text": "Hi"}}}}}, "m1", "T\nHi", nil},
		{"multi paragraph join", map[string]any{"content": []any{
			[]any{map[string]any{"tag": "text", "text": "line1 "}, map[string]any{"tag": "emotion", "emoji_type": "OK"}},
			[]any{map[string]any{"tag": "text", "text": "line2"}},
		}}, "m1", "line1 [OK]\nline2", nil},
		{"empty payload", map[string]any{}, "m1", "", nil},
		{"unknown tag skipped", map[string]any{"content": []any{[]any{map[string]any{"tag": "bogus", "text": "x"}}}}, "m1", "", nil},
		{"non-dict element skipped", map[string]any{"content": []any{[]any{"junk", map[string]any{"tag": "text", "text": "ok"}}}}, "m1", "ok", nil},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			text, media := extractText(t, tc.contentData, tc.messageID)
			if text != tc.wantText {
				t.Errorf("text = %q, want %q", text, tc.wantText)
			}
			if len(media) != len(tc.wantMedia) {
				t.Fatalf("media count = %d, want %d", len(media), len(tc.wantMedia))
			}
		})
	}
}

func TestExtractPostPartsImgBecomesMedia(t *testing.T) {
	text, media := extractPostParts(
		map[string]any{"content": []any{[]any{map[string]any{"tag": "img", "image_key": "v3_imgkey"}}}},
		"om_123")
	if text != "" {
		t.Errorf("text = %q, want empty (img must not leak into text)", text)
	}
	if len(media) != 1 {
		t.Fatalf("media count = %d, want 1", len(media))
	}
	p := media[0]
	if p.Kind != imgateway.ContentTypeImage {
		t.Errorf("kind = %q, want image", p.Kind)
	}
	wantURL := "https://open.feishu.cn/open-apis/im/v1/messages/om_123/resources/v3_imgkey?type=image"
	if p.URL != wantURL {
		t.Errorf("url = %q, want %q", p.URL, wantURL)
	}
	if p.AltText != "v3_imgkey" {
		t.Errorf("alt_text = %q, want v3_imgkey", p.AltText)
	}
}

func TestExtractPostPartsMediaBecomesFile(t *testing.T) {
	_, media := extractPostParts(
		map[string]any{"content": []any{[]any{map[string]any{"tag": "media", "file_key": "fk1", "file_name": "doc.pdf"}}}},
		"om_9")
	if len(media) != 1 {
		t.Fatalf("media count = %d, want 1", len(media))
	}
	p := media[0]
	if p.Kind != imgateway.ContentTypeFile {
		t.Errorf("kind = %q, want file", p.Kind)
	}
	wantURL := "https://open.feishu.cn/open-apis/im/v1/messages/om_9/resources/fk1?type=file"
	if p.URL != wantURL {
		t.Errorf("url = %q, want %q", p.URL, wantURL)
	}
	if p.Filename != "doc.pdf" {
		t.Errorf("filename = %q, want doc.pdf", p.Filename)
	}
}

func TestExtractPostPartsTwoImages(t *testing.T) {
	_, media := extractPostParts(
		map[string]any{"content": []any{[]any{
			map[string]any{"tag": "img", "image_key": "k1"},
			map[string]any{"tag": "img", "image_key": "k2"},
		}}},
		"m")
	if len(media) != 2 {
		t.Fatalf("media count = %d, want 2", len(media))
	}
	base := "https://open.feishu.cn/open-apis/im/v1/messages/m/resources/"
	if media[0].URL != base+"k1?type=image" || media[1].URL != base+"k2?type=image" {
		t.Errorf("urls = %q, %q", media[0].URL, media[1].URL)
	}
}
