package discord

import (
	"strings"
	"testing"
)

// Expected values below were generated by executing the original Python
// source (octop_gateway/channels/discord.py:387 split_discord_text) on the
// same inputs.

func TestSplitDiscordTextShortInput(t *testing.T) {
	cases := []struct {
		name string
		in   string
	}{
		{"plain word", "hello"},
		{"crlf preserved", "a\r\nb"},
		{"no trailing newline", "para1\npara2\npara3"},
		{"exactly at limit", strings.Repeat("a", 2000)},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			chunks, err := SplitDiscordText(tc.in, 2000)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if len(chunks) != 1 {
				t.Fatalf("chunk count = %d, want 1", len(chunks))
			}
			if chunks[0] != tc.in {
				t.Errorf("chunk content mismatch\n got %q\nwant %q", chunks[0], tc.in)
			}
		})
	}
}

func TestSplitDiscordTextEmptyReturnsNoChunks(t *testing.T) {
	chunks, err := SplitDiscordText("", 2000)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(chunks) != 0 {
		t.Errorf("chunk count = %d, want 0", len(chunks))
	}
}

func TestSplitDiscordTextLimitTooSmall(t *testing.T) {
	_, err := SplitDiscordText("x", 31)
	if err == nil {
		t.Fatal("expected error for limit < 32")
	}
	// Python: ValueError("Discord chunk limit must be at least 32")
	if !strings.Contains(err.Error(), "Discord chunk limit must be at least 32") {
		t.Errorf("error = %q, want it to contain the Python message", err.Error())
	}
}

func TestSplitDiscordTextOverLimitByOne(t *testing.T) {
	chunks, err := SplitDiscordText(strings.Repeat("a", 2001), 2000)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(chunks) != 2 {
		t.Fatalf("chunk count = %d, want 2", len(chunks))
	}
	if chunks[0] != strings.Repeat("a", 2000) || chunks[1] != "a" {
		t.Errorf("chunks = [%d chars, %d chars], want [2000, 1]", len(chunks[0]), len(chunks[1]))
	}
}

func TestSplitDiscordTextLineBoundaries(t *testing.T) {
	// limit=32: six lines (30 units) fill chunk 1, remaining two lines go to
	// chunk 2. Splitting happens only on line ends — whole lines kept.
	chunks, err := SplitDiscordText("aaaa\nbbbb\naaaa\nbbbb\naaaa\nbbbb\naaaa\nbbbb\n", 32)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{
		"aaaa\nbbbb\naaaa\nbbbb\naaaa\nbbbb\n",
		"aaaa\nbbbb\n",
	}
	if len(chunks) != len(want) {
		t.Fatalf("chunk count = %d, want %d (%q)", len(chunks), len(want), chunks)
	}
	for i := range want {
		if chunks[i] != want[i] {
			t.Errorf("chunk[%d] = %q, want %q", i, chunks[i], want[i])
		}
	}
}

func TestSplitDiscordTextLongLineCharSplit(t *testing.T) {
	// 100 x's, limit=32 → 32/32/32/4 char-level split without losing content.
	chunks, err := SplitDiscordText(strings.Repeat("x", 100), 32)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{
		strings.Repeat("x", 32),
		strings.Repeat("x", 32),
		strings.Repeat("x", 32),
		"xxxx",
	}
	if len(chunks) != len(want) {
		t.Fatalf("chunk count = %d, want %d", len(chunks), len(want))
	}
	for i := range want {
		if chunks[i] != want[i] {
			t.Errorf("chunk[%d] = %q, want %q", i, chunks[i], want[i])
		}
	}
}

func TestSplitDiscordTextEmojiBudgetedInUTF16Units(t *testing.T) {
	// U+1F600 costs 2 UTF-16 units: 24 emojis = 48 units > 32 → 16 + 8.
	chunks, err := SplitDiscordText(strings.Repeat("\U0001F600", 24), 32)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{
		strings.Repeat("\U0001F600", 16),
		strings.Repeat("\U0001F600", 8),
	}
	if len(chunks) != len(want) {
		t.Fatalf("chunk count = %d, want %d", len(chunks), len(want))
	}
	for i := range want {
		if chunks[i] != want[i] {
			t.Errorf("chunk[%d] = %q, want %q", i, chunks[i], want[i])
		}
	}

	// 1001 emojis = 2002 UTF-16 units > 2000 → 1000 + 1.
	chunks, err = SplitDiscordText(strings.Repeat("\U0001F600", 1001), 2000)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(chunks) != 2 || chunks[0] != strings.Repeat("\U0001F600", 1000) || chunks[1] != "\U0001F600" {
		t.Errorf("emoji 1001 split = %d chunks (%d, %d units), want 1000+1",
			len(chunks), utf16Len(chunks[0]), utf16Len(chunks[1]))
	}
}

func TestSplitDiscordTextBacktickFence(t *testing.T) {
	// Mirrors the Python source (discord.py:412): a ``` fence whose info
	// string contains no backtick IS recognized as an opener, so oversized
	// fenced content is split with the fence closed ("\n```") and reopened
	// ("```python\n") per chunk.
	text := "```python\n" + strings.Repeat("A", 50) + "\nend\n```\n"
	chunks, err := SplitDiscordText(text, 40)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{
		"```python\n" + strings.Repeat("A", 26) + "\n```",
		"```python\n" + strings.Repeat("A", 24) + "\n\n```",
		"```python\nend\n```\n",
	}
	if len(chunks) != len(want) {
		t.Fatalf("chunk count = %d, want %d\nchunks: %q", len(chunks), len(want), chunks)
	}
	for i := range want {
		if chunks[i] != want[i] {
			t.Errorf("chunk[%d] = %q, want %q", i, chunks[i], want[i])
		}
	}
}

func TestSplitDiscordTextTildeFence(t *testing.T) {
	// ~~~ fences are recognized as openers exactly like ``` fences.
	text := "~~~\n" + strings.Repeat("B", 40) + "\n"
	chunks, err := SplitDiscordText(text, 32)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []string{
		"~~~\n" + strings.Repeat("B", 24) + "\n~~~",
		"~~~\n" + strings.Repeat("B", 16) + "\n\n~~~",
	}
	if len(chunks) != len(want) {
		t.Fatalf("chunk count = %d, want %d\nchunks: %q", len(chunks), len(want), chunks)
	}
	for i := range want {
		if chunks[i] != want[i] {
			t.Errorf("chunk[%d] = %q, want %q", i, chunks[i], want[i])
		}
	}
}

func TestSplitDiscordTextBacktickInFenceInfoNotAnOpener(t *testing.T) {
	// A "fence" whose info string contains a backtick is never treated as an
	// opener (Python: "`" not in info fails), so the text stays untouched.
	text := "``` a`b\nhello\n"
	chunks, err := SplitDiscordText(text, 32)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(chunks) != 1 || chunks[0] != text {
		t.Errorf("chunks = %q, want [%q]", chunks, text)
	}
}

func TestSplitDiscordTextRoundtripWithoutFences(t *testing.T) {
	inputs := []string{
		"hello world",
		strings.Repeat("x", 100),
		"aaaa\nbbbb\naaaa\nbbbb\naaaa\nbbbb\naaaa\nbbbb\n",
		strings.Repeat("\U0001F600", 24),
		"a\r\nb\r\nc",
		"tail without newline",
	}
	for _, in := range inputs {
		chunks, err := SplitDiscordText(in, 32)
		if err != nil {
			t.Fatalf("unexpected error for %q: %v", in, err)
		}
		if got := strings.Join(chunks, ""); got != in {
			t.Errorf("roundtrip of %q: got %q", in, got)
		}
	}
}

func TestSplitDiscordTextAllChunksWithinLimit(t *testing.T) {
	inputs := []struct {
		text  string
		limit int
	}{
		{strings.Repeat("word line\n", 400), 64},
		{strings.Repeat("😀😀 mixed é text ", 300), 2000},
		{"```python\n" + strings.Repeat("A", 5000) + "\n```\n", 2000},
	}
	for i, in := range inputs {
		chunks, err := SplitDiscordText(in.text, in.limit)
		if err != nil {
			t.Fatalf("case %d: unexpected error: %v", i, err)
		}
		for j, c := range chunks {
			if n := utf16Len(c); n > in.limit {
				t.Errorf("case %d chunk %d: %d units > limit %d", i, j, n, in.limit)
			}
		}
	}
}
