package memory

import (
	"testing"
	"time"
)

// Expected values in these tests were generated by running the original
// Python implementation (octop-memory 1.0.0) directly, so they pin the Go
// port to byte-identical behaviour.

func TestNormalizeAlias(t *testing.T) {
	tests := []struct{ in, want string }{
		{"ＧＰＴ-4  Ｔest", "gpt-4 test"}, // NFKC full-width → half-width
		{"ß", "ss"},                      // casefold full folding
		{"İstanbul", "i\u0307stanbul"},   // dotted capital I → i + combining dot
		{"  Foo   BAR  ", "foo bar"},     // lowercase + collapse + strip
		{"GPT-4", "gpt-4"},               // punctuation preserved
		{"", ""},                         // total: empty in, empty out
	}
	for _, tt := range tests {
		if got := NormalizeAlias(tt.in); got != tt.want {
			t.Errorf("NormalizeAlias(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestSegmentCJK(t *testing.T) {
	tests := []struct{ in, want string }{
		{"部署方案从docker切换", " 部  署  方  案  从 docker 切  换 "},
		{"plain english", "plain english"},
		{"", ""},
		{"混合text内容", " 混  合 text 内  容 "},
	}
	for _, tt := range tests {
		if got := SegmentCJK(tt.in); got != tt.want {
			t.Errorf("SegmentCJK(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestFTSMatchPhrase(t *testing.T) {
	tests := []struct{ in, want string }{
		{"部署", `" 部  署 "`},
		{`a"b 部署`, `"a""b  部  署 "`},
	}
	for _, tt := range tests {
		if got := FTSMatchPhrase(tt.in); got != tt.want {
			t.Errorf("FTSMatchPhrase(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestParseDatetimeUTC(t *testing.T) {
	tests := []struct {
		in   string
		want time.Time
	}{
		{"2026-06-26T10:00:00+08:00", time.Date(2026, 6, 26, 2, 0, 0, 0, time.UTC)},
		{"2026-06-26", time.Date(2026, 6, 26, 0, 0, 0, 0, time.UTC)},
		{"2026-06-26 10:30:00", time.Date(2026, 6, 26, 10, 30, 0, 0, time.UTC)},
		{"2026-06-26T10:00:00.123456+05:30", time.Date(2026, 6, 26, 4, 30, 0, 123456000, time.UTC)},
		{"2026-06-26T10:00:00Z", time.Date(2026, 6, 26, 10, 0, 0, 0, time.UTC)},
	}
	for _, tt := range tests {
		got, err := ParseDatetimeUTC(tt.in)
		if err != nil {
			t.Errorf("ParseDatetimeUTC(%q) unexpected error: %v", tt.in, err)
			continue
		}
		if !got.Equal(tt.want) {
			t.Errorf("ParseDatetimeUTC(%q) = %v, want %v", tt.in, got, tt.want)
		}
	}
	if _, err := ParseDatetimeUTC("not-a-date"); err == nil {
		t.Error("ParseDatetimeUTC(\"not-a-date\") should fail")
	}
}

func TestAsUtc(t *testing.T) {
	// Naive values (parsed without offset) become UTC — same instant.
	got := AsUtc(time.Date(2026, 6, 26, 10, 0, 0, 0, time.UTC))
	if got.Location() != time.UTC {
		t.Errorf("AsUtc should return UTC location")
	}
	// Non-UTC location converts to the same absolute instant in UTC.
	cst := time.FixedZone("CST", 8*3600)
	got = AsUtc(time.Date(2026, 6, 26, 10, 0, 0, 0, cst))
	want := time.Date(2026, 6, 26, 2, 0, 0, 0, time.UTC)
	if !got.Equal(want) {
		t.Errorf("AsUtc(+08:00) = %v, want %v", got, want)
	}
}
