package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

// MessageRoleType identifies the sender of a message.
type MessageRoleType string

const (
	// MESSAGE_ROLE_SYSTEM identifies a system-level instruction message.
	MESSAGE_ROLE_SYSTEM MessageRoleType = "system"
	// MESSAGE_ROLE_USER identifies messages sent by the end user.
	MESSAGE_ROLE_USER MessageRoleType = "user"
	// MESSAGE_ROLE_ASSISTANT identifies messages generated by the model.
	MESSAGE_ROLE_ASSISTANT MessageRoleType = "assistant"
	// MESSAGE_ROLE_TOOL identifies messages carrying tool results.
	MESSAGE_ROLE_TOOL MessageRoleType = "tool"
)

// Message is a single conversational turn.
type Message struct {
	Role       MessageRoleType
	Content    []ContentParter
	Name       string `json:"name,omitempty"`         // OpenAI-compatible name field (used for tool messages).
	ToolCallID string `json:"tool_call_id,omitempty"` // Identifies the tool call this result belongs to.
}

// MarshalJSON serializes Message to JSON.
func (m Message) MarshalJSON() ([]byte, error) {
	aux := map[string]any{
		"role":    m.Role,
		"content": m.Content,
	}
	if m.Name != "" {
		aux["name"] = m.Name
	}
	if m.ToolCallID != "" {
		aux["tool_call_id"] = m.ToolCallID
	}
	return json.Marshal(aux)
}

// UnmarshalJSON deserializes Message from JSON.
func (m *Message) UnmarshalJSON(data []byte) error {
	aux := struct {
		Role       MessageRoleType   `json:"role"`
		Content    []json.RawMessage `json:"content"`
		Name       string            `json:"name"`
		ToolCallID string            `json:"tool_call_id"`
	}{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	m.Role = aux.Role
	m.Name = aux.Name
	m.ToolCallID = aux.ToolCallID
	for _, raw := range aux.Content {
		part, err := unmarshalContentPart(raw)
		if err != nil {
			return err
		}
		m.Content = append(m.Content, part)
	}
	return nil
}

func (m Message) Text() string {
	var texts []string
	for _, p := range m.Content {
		switch pt := p.(type) {
		case TextPart:
			texts = append(texts, pt.Text)
		case ToolResultPart:
			for _, inner := range pt.Content {
				if tp, ok := inner.(TextPart); ok {
					texts = append(texts, tp.Text)
				}
			}
		case SourcePart:
			// Source parts are metadata, not text content.
		}
	}
	return strings.Join(texts, "\n")
}

// ExtractToolCalls returns all ToolCallPart from the message.
func (m Message) ExtractToolCalls() []ToolCallPart {
	var calls []ToolCallPart
	for _, p := range m.Content {
		if tc, ok := p.(ToolCallPart); ok {
			calls = append(calls, tc)
		}
	}
	return calls
}
func (m Message) ExtractReasoning() string {
	var texts []string
	for _, p := range m.Content {
		if rp, ok := p.(ReasoningPart); ok {
			texts = append(texts, rp.Text)
		}
	}
	return strings.Join(texts, "\n")
}

// HasToolCalls reports whether the message contains any tool calls.
func (m Message) HasToolCalls() bool {
	for _, p := range m.Content {
		if _, ok := p.(ToolCallPart); ok {
			return true
		}
	}
	return false
}

// IsTextOnly reports whether the message contains only TextPart content
// (or no content at all).
func (m Message) IsTextOnly() bool {
	for _, p := range m.Content {
		if _, ok := p.(TextPart); !ok {
			return false
		}
	}
	return true
}

// ContentParter is a union of all possible message content kinds.
type ContentParter interface {
	contentPart()
	MarshalJSON() ([]byte, error)
}

// TextPart is plain text content.
type TextPart struct {
	Text string `json:"text"`
}

func (TextPart) contentPart() {}

// MarshalJSON serializes TextPart to JSON.
func (p TextPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]string{"type": "text", "text": p.Text})
}

// TextContent creates a single-element []ContentParter with a TextPart.
func NewTextContent(text string) []ContentParter {
	if text == "" {
		return nil
	}
	return []ContentParter{TextPart{Text: text}}
}

// ReasoningPart is content produced by a reasoning model.
type ReasoningPart struct {
	Text      string `json:"text"`
	Signature string `json:"signature,omitempty"`
}

func (ReasoningPart) contentPart() {}

// MarshalJSON serializes ReasoningPart to JSON.
func (p ReasoningPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "reasoning", "text": p.Text, "signature": p.Signature})
}

// ImagePart is an image provided to the model.
type ImagePart struct {
	URL      string `json:"url,omitempty"`
	Data     []byte `json:"data,omitempty"`
	MIMEType string `json:"mime_type,omitempty"`
	Detail   string `json:"detail,omitempty"`
}

func (ImagePart) contentPart() {}

// MarshalJSON serializes ImagePart to JSON.
func (p ImagePart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "image", "url": p.URL, "data": p.Data, "mime_type": p.MIMEType, "detail": p.Detail})
}

// AudioPart is audio provided to the model.
type AudioPart struct {
	URL      string `json:"url,omitempty"`
	Data     []byte `json:"data,omitempty"`
	MIMEType string `json:"mime_type,omitempty"`
}

func (AudioPart) contentPart() {}

// MarshalJSON serializes AudioPart to JSON.
func (p AudioPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "audio", "url": p.URL, "data": p.Data, "mime_type": p.MIMEType})
}

// DocumentPart is a document provided to the model.
type DocumentPart struct {
	Data     []byte `json:"data"`
	MIMEType string `json:"mime_type"`
	Name     string `json:"name,omitempty"`
}

func (DocumentPart) contentPart() {}

// MarshalJSON serializes DocumentPart to JSON.
func (p DocumentPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "document", "data": p.Data, "mime_type": p.MIMEType, "name": p.Name})
}

// ToolCallPart represents a tool invocation requested by the model.
type ToolCallPart struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

func (ToolCallPart) contentPart() {}

// MarshalJSON serializes ToolCallPart to JSON.
func (p ToolCallPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "tool_call", "id": p.ID, "name": p.Name, "arguments": p.Arguments})
}

// ToolResultPart carries the result of a tool invocation back to the model.
type ToolResultPart struct {
	ToolCallID string          `json:"tool_call_id"`
	Name       string          `json:"name"`
	Content    []ContentParter `json:"content"`
	IsError    bool            `json:"is_error"`
	StopTurn   bool            `json:"stop_turn,omitempty"`
}

func (ToolResultPart) contentPart() {}

// MarshalJSON serializes ToolResultPart to JSON.
func (p ToolResultPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]any{"type": "tool_result", "tool_call_id": p.ToolCallID, "name": p.Name, "content": p.Content, "is_error": p.IsError})
}

func unmarshalContentPart(raw []byte) (ContentParter, error) {
	var typ struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(raw, &typ); err != nil {
		return nil, err
	}
	switch typ.Type {
	case "text":
		var p TextPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "reasoning":
		var p ReasoningPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "image":
		var p ImagePart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "audio":
		var p AudioPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "document":
		var p DocumentPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "tool_call":
		var p ToolCallPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "tool_result":
		var p ToolResultPart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	case "source":
		var p SourcePart
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, err
		}
		return p, nil
	default:
		return nil, fmt.Errorf("unknown content part type: %q", typ.Type)
	}
}

// UnmarshalJSON deserializes ToolResultPart from JSON.
func (p *ToolResultPart) UnmarshalJSON(data []byte) error {
	aux := struct {
		ToolCallID string            `json:"tool_call_id"`
		Name       string            `json:"name"`
		Content    []json.RawMessage `json:"content"`
		IsError    bool              `json:"is_error"`
	}{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	p.ToolCallID = aux.ToolCallID
	p.Name = aux.Name
	p.IsError = aux.IsError
	for _, raw := range aux.Content {
		part, err := unmarshalContentPart(raw)
		if err != nil {
			return err
		}
		p.Content = append(p.Content, part)
	}
	return nil
}

// NewTextMessage creates a message with the given role and a single text part.
func NewTextMessage(role MessageRoleType, text string) Message {
	return Message{
		Role:    role,
		Content: NewTextContent(text),
	}
}

// SourceType represents the type of source.
type SourceType string

const (
	// SourceTypeURL represents a URL source.
	SourceTypeURL SourceType = "url"
	// SourceTypeDocument represents a document source.
	SourceTypeDocument SourceType = "document"
)

// SourcePart represents a source reference used to generate the response.
type SourcePart struct {
	SourceType SourceType `json:"source_type"`
	ID         string     `json:"id"`
	URL        string     `json:"url,omitempty"`
	Title      string     `json:"title,omitempty"`
}

// MarshalJSON serializes SourcePart to JSON with omitempty for optional fields.
func (p SourcePart) MarshalJSON() ([]byte, error) {
	type alias SourcePart // prevent recursion
	return json.Marshal(struct {
		Type string `json:"type"`
		*alias
	}{
		Type:  "source",
		alias: (*alias)(&p),
	})
}

func (SourcePart) contentPart() {}

// NewToolResultContent creates a ToolResultPart wrapped as a full message.
func NewToolResultContent(toolCallID, name, result string) Message {
	return Message{
		Role: MESSAGE_ROLE_TOOL,
		Content: []ContentParter{ToolResultPart{
			ToolCallID: toolCallID,
			Name:       name,
			Content:    NewTextContent(result),
		}},
	}
}
