package telegram

import "testing"

// Expected values below were generated by executing the original Python
// source (octop_gateway/channels/telegram/format_html.py:
// markdown_to_telegram_html) on the same inputs.

func TestMarkdownToTelegramHTML(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"empty passthrough", "", ""},
		{"html escape", "a < b & c > d", "a &lt; b &amp; c &gt; d"},
		{"bold", "**bold**", "<b>bold</b>"},
		{"italic", "*it*", "<i>it</i>"},
		// Python lookarounds (?<!\w)...(?!\w): a spaced asterisk pair matches.
		{"italic spaced", "a * b * c", "a <i> b </i> c"},
		// lookahead fails when a word char follows the closing delimiter
		{"italic no close", "*a*b", "*a*b"},
		{"bold via underscores", "call __init__ now", "call <b>init</b> now"},
		{"bold italic", "***bi***", "<b><i>bi</i></b>"},
		{"strikethrough", "~~s~~", "<s>s</s>"},
		{"spoiler", "||sp||", "<tg-spoiler>sp</tg-spoiler>"},
		{"headings", "# Title\n###### h6\n#NoSpace", "<b>Title</b>\n<b>h6</b>\n#NoSpace"},
		{"heading needs line start", " # H", " # H"},
		{"horizontal rules", "---\n***\n___", "———\n———\n———"},
		{"bullets", "- item\n* item\n  - indented", "• item\n• item\n  • indented"},
		{
			"code block with language (content escaped)",
			"```go\nfmt.Println(a<b && c>d)\n```",
			"<pre><code class=\"language-go\">fmt.Println(a&lt;b &amp;&amp; c&gt;d)\n</code></pre>",
		},
		{
			"code block without language",
			"```\nplain <text>\n```",
			"<pre>plain &lt;text&gt;\n</pre>",
		},
		{"inline code escaped", "`a<b` and `x&y`", "<code>a&lt;b</code> and <code>x&amp;y</code>"},
		// href is NOT html-escaped (only < and > are percent-encoded); text is
		{"link href keeps ampersand", "[text](https://x.com/a?b=1&c=2)", "<a href=\"https://x.com/a?b=1&c=2\">text</a>"},
		{"link text escaped", "[a<b](u)", "<a href=\"u\">a&lt;b</a>"},
		{"blockquote grouping", "> q1\n> q2\nnotq\n> q3", "<blockquote>q1\nq2</blockquote>\nnotq\n<blockquote>q3</blockquote>"},
		{"bare quote line", ">\n> x", "<blockquote>\nx</blockquote>"},
		// "> " inside a code block is protected behind a placeholder
		{"quote marker inside code block", "```\n> not a quote\n```", "<pre>&gt; not a quote\n</pre>"},
		// Python `.` does not match \n (no DOTALL) so italics cannot span lines
		{"italic cannot span newline", "*a\nb*", "*a\nb*"},
		{"snake case untouched", "snake_case and a_b_c stay", "snake_case and a_b_c stay"},
		{"bold containing italic", "**bold *it* more**", "<b>bold <i>it</i> more</b>"},
		// code block content is shielded from emphasis regexes
		{"emphasis inside code block untouched", "```\n**x**\n```", "<pre>**x**\n</pre>"},
		// emphasis inside a blockquote body still applies afterwards
		{"italic inside quote", "> *i*", "<blockquote><i>i</i></blockquote>"},
		// both delimiters surrounded by word chars: lookbehind fails everywhere
		{"asterisk between words", "x*y*z", "x*y*z"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := MarkdownToTelegramHTML(tc.in); got != tc.want {
				t.Errorf("MarkdownToTelegramHTML(%q)\n got %q\nwant %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestMarkdownToTelegramHTMLCodeBlockLanguageUnicode(t *testing.T) {
	// Python \w* on the fence line matches Unicode word chars.
	got := MarkdownToTelegramHTML("```py\nx = 1\n```")
	want := "<pre><code class=\"language-py\">x = 1\n</code></pre>"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}
